######################################################################
# Automatically generated by qmake (3.0) Fri Oct 11 08:25:24 2013
######################################################################

TEMPLATE = app
TARGET = om
INCLUDEPATH += .

# Input
SOURCES += src/main.cxx
